## Semi-Supervised Learning

Most times, manually labeling a complete dataset can be very time consuming, and in
real life scenarios, time is money. 

We are aiming to partially delete the target feature in
different proportions for each class, and run active and pasive semi-supervised learning
processes. This experiment will help us understand how it performs with our samples.


Our set of samples is not as large as we would like it to be, but it will be useful to study
how to identify the most interesting samples to manually label and leave the rest to the
model, saving the time and effort it takes to fully supervise a dataset

In [1]:
import pandas

In [2]:
data = pandas.read_csv("../data/updated_pollution_dataset.csv")

In [3]:
target_col = data.columns[-1]

distribution = (
    data[target_col]
    .value_counts(dropna=False)
    .rename_axis(target_col)
    .reset_index(name="count")
)

distribution["percentage"] = (distribution["count"] / len(data) * 100).round(2)
distribution

  Air Quality  count  percentage
0        Good   2000        40.0
1    Moderate   1500        30.0
2        Poor   1000        20.0
3   Hazardous    500        10.0

In [4]:
quality_map = {
    "Good": 3,
    "Moderate": 2,
    "Poor": 1,
    "Hazardous": 0
}

data[target_col] = data[target_col].map(quality_map)


data[target_col] = data[target_col].astype("int8")
data[[target_col]].head()

   Air Quality
0            2
1            2
2            2
3            3
4            3

* Target variable partial deletion